### ISSUE TITLE
BIOS information don't processed

### ISSUE THREAD

**Issue by laprion** [OCSInventory-NG/OCSInventory-Server#76]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :
server: Ubuntu 14.04.5 x64
clients: Windows 7, 8.1

### Server informations
Perl version:
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
Mysql / Mariadb / Percona version:
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3

### OCS Inventory informations
Ocs server version : 2.3.1
Ocs client version : 2.3.1

### Problem's description
Hello! All computers don't send information about Motherboard Serial, Manufacturer and Model on server (or send but server don't processed them) in BIOS section.

![bios_client](https://user-images.githubusercontent.com/32697589/31426168-a8bf9d3c-ae7b-11e7-944d-0a42855023b0.jpg)
![bios_server](https://user-images.githubusercontent.com/32697589/31426172-ac20c1d6-ae7b-11e7-980a-9035ceb1e938.jpg)

**Comment by gillesdubois** [comment]
Hi,

Can you generate an XML of an agent inventory and check if Bios data are in the xml ?
Can you check if the data are in the database ? (bios table)

Regards,
Gilles Dubois.

**Comment by laprion** [comment]
In XML Bios data are present, but in the database columns MMANUFACTURER | MMODEL | MSN contains a value NULL.

**Comment by gillesdubois** [comment]
Do you have any log in your apache error log ?

**Comment by laprion** [comment]
Only: Wide character in print at /usr/local/share/perl/5.18.2/Apache/Ocsinventory/Server/System.pm line 264. But they dated Oct 08 06:31:50.308447 2017 and there are a lot of them.

**Comment by gillesdubois** [comment]
Ok thx, I will check this out.

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with the latest version.

Regards,
Gilles Dubois.

**Comment by laprion** [comment]
Hi, problem still there. Some computers display information, most don't.
